COMANDOS BASICOS NUMPY

In [6]:
import numpy as np

Creaccion de Arrays:

numpy.array(): Crea un array a partir de una lista.

In [9]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

numpy.zeros(): Crea un array lleno de ceros.

In [17]:
array_ceros = np.zeros(3)
array_ceros

array([0., 0., 0.])

numpy.ones(): Crea un array lleno de unos.

In [18]:
array_ones = np.ones(3)
array_ones

array([1., 1., 1.])

numpy.empty(): Crea un array vacío.

In [20]:
array_empty = np.empty(3)
array_empty

array([1., 1., 1.])

Operaciones básicas:

array.shape: Devuelve la forma del array.

In [26]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1.shape)

(3, 3)


array.size: Devuelve el número de elementos del array.

In [30]:
print(f'Numero de elementos: {array1.size}')

Numero de elementos: 9


array.dtype: Devuelve el tipo de datos del array.

In [31]:
print(f'Tipos de datos: {array1.dtype}')

Tipos de datos: int64


array.ndim: Devuelve el número de dimensiones del array.

In [32]:
print(f'Dimensiones: {array1.ndim}')

Dimensiones: 2


Operaciones aritméticas:

In [33]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[10,11,12],[13,14,15],[16,17,18]])

array + array: Suma dos arrays.

In [36]:
print(f'Suma:\n{array1 + array2}')

Suma:
[[11 13 15]
 [17 19 21]
 [23 25 27]]


array - array: Resta dos arrays.

In [37]:
print(f'Resta:\n{array1 - array2}')

Suma:
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


array * array: Multiplica dos arrays.

In [38]:
print(f'Multi:\n{array1 * array2}')

Multi:
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


array / array: Divide dos arrays.

In [39]:
print(f'Divi:\n{array1 / array2}')

Divi:
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


Operaciones estadísticas:

In [42]:
array_e1 = np.array([[11,20,34],[50,70,35,],[67,47,99]])
array_e2 = np.array([[5,8,3],[13,55,55,],[6,7,9]])

numpy.mean(): Calcula la media de un array.

In [44]:
print(f'Media e1:\n{array_e1.mean()}')
print(f'Media e2:\n{array_e2.mean()}')

Media e1:
48.111111111111114
Media e2:
17.88888888888889


numpy.median(): Calcula la mediana de un array.

In [48]:
median1 = np.median(array_e1)
median2 = np.median(array_e2)
print(f'Median e1:\n{median1}')
print(f'Median e2:\n{median2}')

Median e1:
47.0
Median e2:
8.0


numpy.std(): Calcula la desviación estándar de un array.

In [51]:
desvi_1 = np.std(array_e1)
desvi_2 = np.std(array_e2)
print(f'Desviacion e1:\n{desvi_1}')
print(f'Desviacion e2:\n{desvi_2}')

Desviacion e1:
25.752861521454463
Desviacion e2:
20.008023082111862


Indexación y rebanado:

In [52]:
array_index = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

array[i]: Accede al elemento i-ésimo del array.

In [62]:
print(array_index[0])
print(array_index[1])
print(array_index[2])
print(array_index[3])

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


array[i:j]: Accede a los elementos del array desde i hasta j-1.

In [66]:
print(array_index[1:4])

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
